apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio.yaml
- istio-operator.yaml
- namespace.yaml
- gateway.yaml
- peerauthentication.yaml
- kiali.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.15/samples/addons/prometheus.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.15/samples/addons/jaeger.yaml
patches:
- target:
    version: v1
    kind: Service
    name: istio-ingressgateway
    namespace: istio-system
  patch: |-
    - op: replace
      path: /spec/ports
      value: 
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 8080


