apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api-kustomization.yaml
- database-kustomization.yaml
- flux-crds.yaml
- github-repo.yaml
- ingress-kustomization.yaml
- ui-kustomization.yaml
